<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pl.symentis.mapreduce</groupId>
        <artifactId>mapreduce</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>mapreduce-client-docker</artifactId>
    <packaging>pom</packaging>

    <name>mapreduce-server-docker</name>
    <description>Docker image build for mapreduce-server</description>

    <dependencies>
        <dependency>
            <groupId>pl.symentis.mapreduce</groupId>
            <artifactId>mapreduce-server</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>pl.symentis.mapreduce</groupId>
            <artifactId>mapreduce-wordcount-bundle</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>pl.symentis.mapreduce</groupId>
            <artifactId>mapreduce-wordcount</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.pyroscope</groupId>
            <artifactId>agent</artifactId>
            <version>2.1.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>copy-big-txt</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>pl.symentis.mapreduce</groupId>
                                    <artifactId>mapreduce-wordcount</artifactId>
                                    <version>${project.version}</version>
                                    <type>test-jar</type>
                                    <classifier>tests</classifier>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/test-resources</outputDirectory>
                                    <includes>**/big.txt</includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-config</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>pl.symentis.mapreduce</groupId>
                                    <artifactId>mapreduce-server</artifactId>
                                    <version>${project.version}</version>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/config</outputDirectory>
                                    <includes>**/defaults.cfg</includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.46.0</version>
                <executions>
                    <execution>
                        <id>build-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <images>
                        <image>
                            <name>mapreduce-client:${project.version}</name>
                            <build>
                                <dockerFile>${project.basedir}/src/main/docker/Dockerfile</dockerFile>
                                <assembly>
                                    <descriptor>${project.basedir}/src/main/assembly/docker-assembly.xml</descriptor>
                                </assembly>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>