name: Java CI

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4.1.1
